### PR TITLE
Add tpope/vim-repeat compatibility

### PR DESCRIPTION
**Pull request by wilywampa**

### CODE REVIEW

**Comment by tommcdo** [comment]
Exchange repeats naturally. Can you give more detail about what this is doing?

**Comment by wellle** [comment]
@tommcdo: I noticed some issues from time to time too. This PR could fix them.

Here's an example:

#### before
```
foo
bar
```
With the surround plugin, type `yssb` to surround the first lines in parentheses. Pressing `.` will repeat it to `((foo))`. Not press `cxx` to mark the current line for exchange. Pressing `.` on the second line should finish the exchange, but it will surround the second line instead:

#### after
```
((foo))
(bar)
```
#### expected
```
bar
((foo))
```

**Comment by tommcdo** [comment]
Interesting... I'm curious about what's going on here, but for now I'll merge this in.

**Comment by wilywampa** [comment]
Sure. When calling `repeat#set()`, vim-repeat saves the value of `b:changedtick` in `g:repeat_tick`. The next time `.` is pressed, vim-repeat checks if `b:changedtick` has incremented since being saved to `g:repeat_tick`. If it has, then it assumes that no repeatable action has occurred since `repeat#set()` was called and it repeats what is in `g:repeat_sequence`, otherwise it uses Vim's `.` functionality.

The problem addressed in this PR is that if the action before using Exchange was saved in vim-repeat and then Exchange is used for the first half of an exchange, `b:changedtick` is not incremented so when the user pressed `.` vim-repeat fires off `g:change_sequence` instead of letting Vim repeat the Exchange action. Calling `repeat#invalidate()` resets `g:repeat_tick` so that vim-repeat knows it should let Vim do its thing instead of using `g:repeat_sequence`.

**Pull request merged**
